### ISSUE TITLE
[QUESTION] Does pytest-django include this feature now?

### ISSUE THREAD

**Issue by luarx** [rlucioni/pytest-django-ordering#13]
I have seen that maybe is already included
https://pytest-django.readthedocs.io/en/latest/changelog.html#v3-5-0-2019-06-03

What do you think? Or is it about another functionality?

**Comment by rlucioni** [comment]
The full history of this issue is at https://github.com/pytest-dev/pytest-django/issues/214. Similar functionality was added to pytest-django by https://github.com/pytest-dev/pytest-django/pull/223, but as of that PR the resulting ordering was still wrong. I don't think it supports `TransactionTestCase`, which is why this plugin [runs last](https://github.com/rlucioni/pytest-django-ordering/blob/966896361313f14e72e1a535ad2bdfbe10612659/pytest_django_ordering/plugin.py#L9-L10) if you use it.

**Comment by luarx** [comment]
Yeah, I tried the last `pytest-django `version and it still doesn't run `TransactionTestCase `as expected but just to confirm that it was not because of a misconfiguration from my side...

Thank you for your fast answer! **Your plugin rocks** :)
